### ISSUE TITLE
RESERVE_FEE_CONDITION_FAILED on --push-tx

### ISSUE THREAD

**Issue by farmerdiamonds** [Yakuhito/tibet#7]
Chia rpc version 1.8.0
Tibetswap venv Chia version 1.7.0
Creating the offer went without issues but when I try to --push-tx the offer to add liquidity to a specific pair I get this Error:

python3 tibet.py deposit-liquidity --offer offer.txt --push-tx --asset-id xxx --fee 100
Depositing liquidity...
Current pair coin id: xxx
No need to generate new offer.
Pair state updated since last sync; saving it...
Are you sure you want to broadcast this spend? (Yes): Yes
Pushing tx...
Traceback (most recent call last):
  File "/home/ubuntu/tibet/tibet.py", line 975, in <module>
    cli()
  File "/home/ubuntu/tibet/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/tibet/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/tibet/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/tibet/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/tibet/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/tibet/tibet.py", line 398, in deposit_liquidity
    asyncio.run(_deposit_liquidity(asset_id, offer, xch_amount, token_amount, push_tx, fee, use_fee_estimate))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/tibet/tibet.py", line 516, in _deposit_liquidity
    resp = await full_node_client.push_tx(sb)
  File "/home/ubuntu/tibet/venv/lib/python3.10/site-packages/chia/rpc/full_node_rpc_client.py", line 216, in push_tx
    return await self.fetch("push_tx", {"spend_bundle": spend_bundle.to_json_dict()})
  File "/home/ubuntu/tibet/venv/lib/python3.10/site-packages/chia/rpc/rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'Failed to include transaction xxx, error RESERVE_FEE_CONDITION_FAILED', 'success': False}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9bac9481c0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f9bac906620>, 1105943.272924501)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f9bac948220>

**Comment by Yakuhito** [comment]
Hey! It might be that the price has changed, or that the fee is different than what you provided. Try to cancel the current offer & create a new one via the CLI. Let me know if it works

**Comment by Yakuhito** [comment]
Hey! I fixed a bug a while ago that might be connected to this - is the issue still occurring in the latest version?

**Comment by farmerdiamonds** [comment]
No more error, the issue is fixed now. Thank you!
